---
title: "Final_Project"
author: "Nicole Lusk"
date: "2025-11-18"
output: html_document
---

# Data Cleaing
```{r setup, include=FALSE}
library("here")
library("haven")
library("tidyverse")
#install.packages("stargazer")
#library(stargazer)
Demographics<-read_xpt(here("DEMO_L.xpt"))
Fasting<-read_xpt(here("FASTQX_L.xpt"))
Insulin<-read_xpt(here("INS_L.xpt"))
Cholesterol<-read_xpt(here("TCHOL_L.xpt"))
Diabetes<-read_xpt(here("DIQ_L.xpt"))


FullData_df<-Demographics|>
  full_join(Fasting, by = "SEQN")|>
  full_join(Insulin, by = "SEQN")|>
  full_join(Cholesterol, by = "SEQN")|>
  full_join(Diabetes, by = "SEQN")

Data_df<-FullData_df|> 
  select("SEQN", "RIAGENDR", "RIDAGEYR", "PHQ020", "PHACOFHR", "PHQ030", "PHAALCHR", "PHAFSTHR", "LBXTC", "LBXIN", "DIQ010", "DIQ050", "DIQ160")|>
  rename("Sequence" = SEQN,
         "Sex" = RIAGENDR,
         "Age" = RIDAGEYR,
        "Coffee_or_Tea_Factor" = PHQ020, "Hrs_CoffeeTea" = PHACOFHR, 
        "Alcohol_Factor" = PHQ030, "Hrs_Alcohol" = PHAALCHR,
        "Hrs_Food" = PHAFSTHR, 
        "Cholesterol" = LBXTC,
        "Insulin" = LBXIN,
        "Diabetes" = DIQ010, "Taking_Insulin" = DIQ050, "Prediabetes" = DIQ160)|>
  mutate(Sex = case_when(Sex == 1 ~"male", 
                         Sex == 2 ~ "female"),
         Coffee_or_Tea_Factor = case_when(Coffee_or_Tea_Factor == 1 ~ "yes",
                                          Coffee_or_Tea_Factor == 2 ~"no",
                                          .default = NA),
         Alcohol_Factor = case_when(Alcohol_Factor == 1 ~ "yes",
                                 Alcohol_Factor == 2 ~ "no", 
                                 .default = NA),
         Diabetes = ifelse(Diabetes == 1, "yes", "other"),
         Prediabetes = ifelse(Prediabetes == 1, "yes", "other"),
         Taking_Insulin = ifelse(Taking_Insulin == 1, "yes", "other"))
```

# Models
```{r}
Cholesterol_lm<-lm(Cholesterol ~ Hrs_Food, data = Data_df)
Insulin_lm<-lm(log(Insulin) ~ Hrs_Food, data = Data_df)
```

# Cholesterol Model
```{r}
Cholesterol_lm
summary(Cholesterol_lm)
```

## By Sex 
### Female
```{r}
Cholesterol_female_lm <- lm(Cholesterol ~ Hrs_Food, data = Data_df, Sex == "female")
summary(Cholesterol_female_lm)
```

### Male 
```{r}
Cholesterol_male_lm <- lm(Cholesterol ~ Hrs_Food, data = Data_df, Sex == "male")
summary(Cholesterol_male_lm)
```

## Age 
```{r}
Data_df<-Data_df|> filter(Age >= 18)|>
  mutate(Age_Group = if_else(Age > 65, "retired", "working")
  )
```

### Working
```{r}
Cholesterol_work_lm <- lm(Cholesterol ~ Hrs_Food, data = Data_df, Age_Group == "working")
summary(Cholesterol_work_lm)
```
### Retired
```{r}
Cholesterol_retired_lm <- lm(Cholesterol ~ Hrs_Food, data = Data_df, Age_Group == "retired")
summary(Cholesterol_retired_lm)
```

## Diabetes 
### Yes
```{r}
Cholesterol_retired_lm <- lm(Cholesterol ~ Hrs_Food, data = Data_df, Diabetes == "yes")
summary(Cholesterol_retired_lm)
```

```{r}
Cholesterol_retired_lm <- lm(Cholesterol ~ Hrs_Food, data = Data_df, Diabetes == "other")
summary(Cholesterol_retired_lm)
```


# Insulin Model
```{r}
Insulin_lm
summary(Insulin_lm)
```

## By Sex 
### Female
```{r}
Insulin_female_lm <- lm(log(Insulin) ~ Hrs_Food, data = Data_df, Sex == "female")
summary(Insulin_female_lm)
```

### Male 
```{r}
Insulin_male_lm <- lm(log(Insulin) ~ Hrs_Food, data = Data_df, Sex == "male")
summary(Insulin_male_lm)
```
## Age 

### Working
```{r}
Insulin_work_lm <- lm(log(Insulin) ~ Hrs_Food, data = Data_df, Age_Group == "working")
summary(Insulin_work_lm)
```
### Retired
```{r}
Insulin_retired_lm <- lm(log(Insulin) ~ Hrs_Food, data = Data_df, Age_Group == "retired")
summary(Insulin_retired_lm)
```

## Diabetes 
### Yes
```{r}
Insulin_retired_lm <- lm(log(Insulin) ~ Hrs_Food, data = Data_df, Diabetes == "yes")
summary(Insulin_retired_lm)
```

```{r}
Insulin_retired_lm <- lm(log(Insulin) ~ Hrs_Food, data = Data_df, Diabetes == "other")
summary(Insulin_retired_lm)
```
# Graphs

## Cholesterol 

```{r}
ggplot(data = Data_df, aes(x = Hrs_Food, y = Cholesterol))+
  geom_point()+
  theme_minimal()+
  labs(title = "Fasting vs. Cholesterol") + 
  geom_smooth(method = "lm")
```

### Sex 
```{r}
ggplot(data = Data_df, aes(x = Hrs_Food, y = Cholesterol))+
  geom_point()+
  theme_minimal()+
  labs(title = "Fasting vs. Cholesterol") + 
  facet_wrap(~ Sex) +
  geom_smooth(method = "lm")
```

### Age
```{r}
ggplot(data = Data_df, aes(x = Age, y = Cholesterol))+
  geom_point()+
  theme_minimal()+
  labs(title = "Age vs. Cholesterol") + 
  geom_smooth(method = "lm")
```
```{r}
ggplot(data = Data_df, aes(x = Age, y = Cholesterol))+
  geom_point()+
  theme_minimal()+
  labs(title = "Age vs. Cholesterol") + 
  facet_wrap(~ Age_Group) +
  geom_smooth(method = "lm")
```



## Insulin
```{r}
ggplot(data = Data_df, aes(x = Hrs_Food, y = log(Insulin)))+
  geom_point()+
  theme_minimal()+
  labs(title = "Fasting vs. Insulin") +
  geom_smooth(method = "lm")
```
### Sex
```{r}
ggplot(data = Data_df, aes(x = Hrs_Food, y = log(Insulin)))+
  geom_point()+
  theme_minimal()+
  labs(title = "Fasting vs. Insulin") +
  facet_wrap(~ Sex) +
  geom_smooth(method = "lm")
```

```{r}
ggplot(data = Data_df, aes(x = Hrs_Food, y = log(Insulin)))+
  geom_point()+
  theme_minimal()+
  labs(title = "Fasting vs. Insulin") +
  facet_wrap(~ Age_Group) +
  geom_smooth(method = "lm")
```

